<?php
/** @var \App\Entity\Product $product */
?>
<div class="row">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <a href="<?php echo $this->url('products.create');?>" class="btn btn-primary">
                <i class="fa fa-plus-circle"></i> Novo
            </a>
        </div>
        <div class="panel-body">
            <?php
            echo $this->form()->openTag(new \Zend\Form\Form());
            echo $this->form()->closeTag();
            ?>
            <table class="table table-bordered">
                <tbody>
                <tr>
                    <th>Nome</th>
                    <th>Preço</th>
                    <th>Descrição</th>
                    <th>Ações</th>
                </tr>
                <?php foreach ($this->products as $product): ?>
                    <tr>
                        <td><?php echo $this->escapeHtml($product->getName()); ?></td>
                        <td><?php echo $product->getPrice(); ?></td>
                        <td><?php echo $product->getDescription(); ?></td>
                        <td>
                            <a href="<?php echo $this->url('products.update', ['id' => $product->getId()]);?>">Editar</a> |
                            <a href="<?php echo $this->url('products.delete', ['id' => $product->getId()]);?>">Excluir</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>